### ISSUE TITLE
Not possible to listen to the recording

### ISSUE THREAD

**Issue by Mautefort** [justinhunt/moodle-qtype_poodllrecording#2] opened 2017-05-11 20:47 UTC
Hello,

I made some questions using PoodLL recording and unfortunately, after saving the recording, it's impossible to listen to it at the end of the exercice. In the time bar of the mp3 player, it always shows 0 seconds.

I'm using Moodle 2.9.

Thank you for your help !

**Comment by justinhunt** [comment] 2017-09-14 00:33
Sorry I missed this. For issues like this its not clearly a bug and could be caused by a number of situations. Its best to contact us first via https://poodll.com/contact. We are more set up to help you there.  I will close this now, but get back in touch via the contact page if the problem persists

**Closed as completed by justinhunt** 2017-09-14 00:33 UTC
