### ISSUE TITLE
Last Poodll question drawing is saved when more the one question is on the same page

### ISSUE THREAD

**Issue by nadavkav** [justinhunt/moodle-qtype_poodllrecording#3] opened 2017-06-21 22:20 UTC
Taking a quiz, with two or more Poodll questions on the same page, only the last Poodll question on the page is saved and displayed in the student quiz attempt review.

No errors, while questions are submitted and automatically saved (after any change).
Weird.

Moodle 3.3 + 
$plugin->version   = 2016112701;
$plugin->requires  = 2016052300;//moodle 3.1.0
$plugin->component = 'qtype_poodllrecording';
$plugin->maturity  = MATURITY_STABLE;
$plugin->release   = '3.0.1 (Build 2016112701)';
$plugin->dependencies = array('filter_poodll' => 2016081401);

**Comment by ishinegirl** [comment] 2017-06-21 23:06
Thats not good!! Thanks for the report. What version of the Poodll filter are you running Nadav?

**Comment by justinhunt** [comment] 2017-06-21 23:08
Thats not good!! Thanks for the report. What version of the Poodll filter are you running Nadav?

**Comment by nadavkav** [comment] 2017-06-22 06:57
I am using all the Poodll plugins. they are all set to track poodll3 branch, so... latest version of that branch.

**Comment by nadavkav** [comment] 2017-06-22 07:00
filter/poodll
$plugin->version   = 2017052201;
$plugin->requires  = 2016052300;//moodle 3.1.0
$plugin->component = 'filter_poodll'; 
$plugin->maturity  = MATURITY_STABLE;
$plugin->release   = '3.0.42(Build 2017052201)';
(And question/type/poodllrecording version is already pasted in the initial comment)

**Comment by nadavkav** [comment] 2017-06-26 18:35
Hi Justin, did you have any time to look at this? andy insights?

**Comment by justinhunt** [comment] 2017-06-28 21:55
Sorry for the delay. I tested last night with audio and could not reproduce the problem. However looking back at the title of the issue, this was with a whiteboard. So  I will retest and get back to you. Sorry I can't move as quickly on these things as I would like.

**Comment by nadavkav** [comment] 2017-06-28 22:03
It's all good dear justin :-)
Thank you for looking into this.

**Comment by nadavkav** [comment] 2017-07-08 15:01
Ping :-)

**Comment by justinhunt** [comment] 2017-07-10 05:03
Hi Nadav. I could find the cause of this and it should be fixed today in the Poodll filter. Do you get it from Github or Moodle.org for your sites?

**Comment by justinhunt** [comment] 2017-07-10 14:35
Hi Nadav, this is now fixed in the Poodll3 branch of the Poodll filter. https://github.com/justinhunt/moodle-filter_poodll/commit/8756a4d34b97e387c1d7ef68d8af1b26f4c0d33c

Thanks for reporting it. I will push it to Moodle.org soon. Sooner if you are in a hurry to get it from there. :)

**Closed as completed by justinhunt** 2017-07-10 14:35 UTC

**Comment by nadavkav** [comment] 2017-07-10 18:50
Bless you dear friend!
